import AuthSessionProvider from "@/components/auth/auth-session-provider";
import AuthProvider from "@/context/auth-provider";
import StyledComponentsRegistry from "@/lib/antd-registry";
import theme from "@/lib/theme-config";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Injury Tracking System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthSessionProvider>
        <ConfigProvider theme={theme}>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <StyledComponentsRegistry>
              <AuthProvider>{children}</AuthProvider>
            </StyledComponentsRegistry>
          </body>
        </ConfigProvider>
      </AuthSessionProvider>
    </html>
  );
}
